Laura/78 add algolia search support 1
suborbital/docs pull request #120
Opened 2022-04-07 02:21 UTC by LauraLangdon

Referred to env vars for DocSearch secrets.

2022-04-07 16:42 UTC, arbourd commented
It seems that the build step is failing due to:
```
Error:  ValidationError: "algolia.apiKey" is required
```

2022-04-07 16:43 UTC, arbourd commented on website/docusaurus.config.js
> +     },
```suggestion
    },
```

2022-04-07 16:44 UTC, arbourd commented on website/docusaurus.config.js
> +     },
some spacing stuff
```suggestion
    algolia: {
      appId: process.env.DOCSEARCH_APP_ID,
      apiKey: process.env.DOCSEARCH_API_KEY,
      indexName: 'suborbital',
      contextualSearch: true
    },
```

2022-04-07 16:54 UTC, LauraLangdon commented
> It seems that the build step is failing due to:
> 
> ```
> Error:  ValidationError: "algolia.apiKey" is required
> ```
> 
> This is probably because the env var is `null` or `""`, which makes sense because we haven't provided it in this PR.
> 
> #119 would need to be merged first but you can combine them into one PR here which would test the whole flow.

I've searched up "combine pull requests" but I'm mostly finding GitHub actions to do this. Is there a specific way you had in mind?

2022-04-09 00:38 UTC, LauraLangdon commented
Woohoo, the connection is made! [Obligatory Elastica](https://youtu.be/ilKcXIFi-Rc) (why doesn't YouTube have an embed option for GitHub? 😛).

I'll work on setting up a crawl on Monday.

2022-04-12 02:44 UTC, LauraLangdon commented
The tests all passed on Friday but failed today, so something's buggy. Maybe related: I'm now getting ```[ERROR] ValidationError: "algolia.apiKey" is required``` when I run `npm start` on the branch I've been working on this in, despite having set up the secrets in GitHub for for the API key and the appID. 🤔

2022-04-12 06:06 UTC, flaki requested changes
There is that pesky `package-lock.json` again! You will need to remove those changes from the PR.

Also let's move the link checker to its own PR.

Looks good otherwise!

I have updated the docs to use the latest Docusaurus Beta 18 to make sure the crawler on the public site gets everything right. Because of this you will need to rebase the branch on `main` (and will probably see conflicts due to package-lock.json, you should be able to discard your local changes and go with the file on `main`).

I had to tweak the [crawler configuration](https://crawler.algolia.com/admin/crawlers/) from the [original](https://docsearch.algolia.com/docs/templates/#docusaurus-v2-template) to have it correctly pick up the headings, it's still not perfect but much better, and we should spend some thought on #64 and generally on tweaking the docs structure in the coming weeks.

![image](https://user-images.githubusercontent.com/2089432/162890876-1d5023ad-1ea2-422e-9913-999c914541a2.png)
[The search in the preview now works as expected](https://suborbital.github.io/docs/laura/78-add-algolia-search-support-1/) so let's get this merged!

2022-04-12 14:54 UTC, LauraLangdon commented
> There is that pesky `package-lock.json` again! You will need to remove those changes from the PR.

Oops! Will do.
 
> Also let's move the link checker to its own PR.

The PR for the link checker is already merged; I'm not sure how it ended up here. 
 
> I have updated the docs to use the latest Docusaurus Beta 18 to make sure the crawler on the public site gets everything right. Because of this you will need to rebase the branch on `main` (and will probably see conflicts due to package-lock.json, you should be able to discard your local changes and go with the file on `main`).

Great! I'll give that a go.

> I had to tweak the [crawler configuration](https://crawler.algolia.com/admin/crawlers/) from the [original](https://docsearch.algolia.com/docs/templates/#docusaurus-v2-template) to have it correctly pick up the headings, it's still not perfect but much better, and we should spend some thought on #64 and generally on tweaking the docs structure in the coming weeks.
> 

I'll check that out!

> ![image](https://user-images.githubusercontent.com/2089432/162890876-1d5023ad-1ea2-422e-9913-999c914541a2.png) [The search in the preview now works as expected](https://suborbital.github.io/docs/laura/78-add-algolia-search-support-1/) so let's get this merged!

Woohoo!

2022-04-12 23:19 UTC, LauraLangdon commented on .github/workflows/links.yml
> +        run: exit ${{ steps.lychee.outputs.exit_code }}
Done!

2022-04-14 01:42 UTC, flaki commented
Closing in favor of #126

2022-04-14 01:42 UTC, closed without merging